name: Custom Rom Builder Samsung Galaxy A11/M11

on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
      GSI:
        description: 'direct link for Gsi image '
        required: true
        default: 'https://sourceforge.net/projects/misterztr-gsi/files/PixelOS/Android%2014/PixelOS_Beta_treble_arm64_bN-14.0-20231114.img.xz'        
      ARCH:
        description: 'ARM64 or ARM32?'
        required: true
        default: '64'                
      NAME:
        description: 'PIXEL_OS_14_SAMSUNG_GALAXY_M11'
        required: true
        default: 'PIXEL_OS_14_SAMSUNG_M11_GAPPS'                

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip xz-utils unzip p7zip-full wget
        
    - name: Preparing Files
      run: |
        wget https://sourceforge.net/projects/samsung-galaxy-a01-m01/files/a11q.zip
        git clone https://github.com/smiley9000/Custom-Rom-Builder-For-Samsung-Galaxy-A11-M11
        unzip a11q.zip
        rm -r a11q.zip

    - name: Downloading your GSI
      run: |
        wget -P "./temp" ${{ github.event.inputs.GSI }} 
        chmod 755 *
        chmod 755 ./bin/*

    - name: Building
      run: |
        ./arm${{ github.event.inputs.ARCH }}_git
        
    - name: Uploading The Zip
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.NAME }}   # Replace with a suitable name
        path: ./zip/Custom_Rom_SDM450.zip
